# Generated by Django 3.0.8 on 2020-07-10 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_file', models.FileField(upload_to='uploads/')),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('uploader', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=200)),
                ('visibility', models.CharField(choices=[('1', 'public'), ('2', 'private'), ('3', 'followers')], max_length=100)),
                ('creator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('playlist_songs', models.ManyToManyField(to='music.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('follow', models.ManyToManyField(blank=True, related_name='_followers_follow_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
